// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCluster(arg1, arg2) {
  return window['go']['main']['App']['AddCluster'](arg1, arg2);
}

export function ConnectCluster(arg1, arg2) {
  return window['go']['main']['App']['ConnectCluster'](arg1, arg2);
}

export function DeleteCluster(arg1) {
  return window['go']['main']['App']['DeleteCluster'](arg1);
}

export function GetBasePath() {
  return window['go']['main']['App']['GetBasePath']();
}

export function GetPodDetails(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPodDetails'](arg1, arg2, arg3);
}

export function GetWorkloads(arg1) {
  return window['go']['main']['App']['GetWorkloads'](arg1);
}

export function ListClusters() {
  return window['go']['main']['App']['ListClusters']();
}

export function RefreshOverview(arg1) {
  return window['go']['main']['App']['RefreshOverview'](arg1);
}

export function RenameCluster(arg1, arg2) {
  return window['go']['main']['App']['RenameCluster'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetBasePath(arg1) {
  return window['go']['main']['App']['SetBasePath'](arg1);
}

export function StartPodsStream(arg1, arg2) {
  return window['go']['main']['App']['StartPodsStream'](arg1, arg2);
}

export function StopPodsStream() {
  return window['go']['main']['App']['StopPodsStream']();
}
