// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCluster(arg1, arg2) {
  return window['go']['main']['App']['AddCluster'](arg1, arg2);
}

export function CompleteClusterKubectl(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompleteClusterKubectl'](arg1, arg2, arg3);
}

export function ConnectCluster(arg1, arg2) {
  return window['go']['main']['App']['ConnectCluster'](arg1, arg2);
}

export function DebugNode(arg1, arg2) {
  return window['go']['main']['App']['DebugNode'](arg1, arg2);
}

export function DeleteCluster(arg1) {
  return window['go']['main']['App']['DeleteCluster'](arg1);
}

export function DeleteDeploymentResource(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteDeploymentResource'](arg1, arg2, arg3);
}

export function DeletePodResource(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePodResource'](arg1, arg2, arg3);
}

export function DeleteWorkloadResource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteWorkloadResource'](arg1, arg2, arg3, arg4);
}

export function ExecClusterKubectl(arg1, arg2) {
  return window['go']['main']['App']['ExecClusterKubectl'](arg1, arg2);
}

export function ExecPodCommand(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExecPodCommand'](arg1, arg2, arg3, arg4, arg5);
}

export function GetBasePath() {
  return window['go']['main']['App']['GetBasePath']();
}

export function GetClusterConfig(arg1) {
  return window['go']['main']['App']['GetClusterConfig'](arg1);
}

export function GetClusterEvents(arg1, arg2) {
  return window['go']['main']['App']['GetClusterEvents'](arg1, arg2);
}

export function GetDeploymentDetails(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDeploymentDetails'](arg1, arg2, arg3);
}

export function GetDeploymentLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDeploymentLogs'](arg1, arg2, arg3, arg4);
}

export function GetDeploymentResources(arg1, arg2) {
  return window['go']['main']['App']['GetDeploymentResources'](arg1, arg2);
}

export function GetNodeDetail(arg1, arg2) {
  return window['go']['main']['App']['GetNodeDetail'](arg1, arg2);
}

export function GetNodeResources(arg1) {
  return window['go']['main']['App']['GetNodeResources'](arg1);
}

export function GetPodDetails(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPodDetails'](arg1, arg2, arg3);
}

export function GetPodLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPodLogs'](arg1, arg2, arg3, arg4);
}

export function GetWorkloadDetails(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetWorkloadDetails'](arg1, arg2, arg3, arg4);
}

export function GetWorkloadLogs(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetWorkloadLogs'](arg1, arg2, arg3, arg4, arg5);
}

export function GetWorkloadResources(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetWorkloadResources'](arg1, arg2, arg3);
}

export function GetWorkloads(arg1) {
  return window['go']['main']['App']['GetWorkloads'](arg1);
}

export function ListClusters() {
  return window['go']['main']['App']['ListClusters']();
}

export function RefreshOverview(arg1) {
  return window['go']['main']['App']['RefreshOverview'](arg1);
}

export function RenameCluster(arg1, arg2) {
  return window['go']['main']['App']['RenameCluster'](arg1, arg2);
}

export function RestartWorkload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RestartWorkload'](arg1, arg2, arg3, arg4);
}

export function SavePodLogsFile(arg1, arg2) {
  return window['go']['main']['App']['SavePodLogsFile'](arg1, arg2);
}

export function ScaleDeployment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScaleDeployment'](arg1, arg2, arg3, arg4);
}

export function ScaleWorkload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ScaleWorkload'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetBasePath(arg1) {
  return window['go']['main']['App']['SetBasePath'](arg1);
}

export function SetCronJobSuspendResource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetCronJobSuspendResource'](arg1, arg2, arg3, arg4);
}

export function StartPodLogsStream(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartPodLogsStream'](arg1, arg2, arg3, arg4);
}

export function StartPodsStream(arg1, arg2) {
  return window['go']['main']['App']['StartPodsStream'](arg1, arg2);
}

export function StopPodLogsStream() {
  return window['go']['main']['App']['StopPodLogsStream']();
}

export function StopPodsStream() {
  return window['go']['main']['App']['StopPodsStream']();
}

export function TriggerCronJobResource(arg1, arg2, arg3) {
  return window['go']['main']['App']['TriggerCronJobResource'](arg1, arg2, arg3);
}

export function UpdateClusterConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateClusterConfig'](arg1, arg2);
}

export function UpdateDeploymentManifest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateDeploymentManifest'](arg1, arg2, arg3, arg4);
}

export function UpdateWorkloadManifest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateWorkloadManifest'](arg1, arg2, arg3, arg4, arg5);
}
